version: "3.7"

services:
  static_file_server:
    container_name: static_file_server
    build: .
    environment:
      - HOSTNAME=static_file_server
    volumes:
      - "data:/data/"

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
      - MINIO_SERVER_ACCESS_KEY=access-key
      - MINIO_SERVER_SECRET_KEY=secret-key
      - MINIO_DEFAULT_BUCKETS=static-files
      - MINIO_FORCE_NEW_KEYS=yes
    volumes:
      - "data:/data/"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - static_file_server

volumes:
  data:
    driver: local